name: Android Production Build

# Trigger automático en push a master con cambios en mobile o shared
on:
  push:
    branches:
      - master
    paths:
      - apps/mobile/**
      - packages/shared/**
      - '!**/*.md'

jobs:
  build_android:
    type: build
    params:
      platform: android
      profile: production
